name: second_one
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # حزم اللغات والـ Localizations
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2  # تم الإبقاء على إصدار واحد مستقر متوافق مع البيئة لديك

  # حزم النظام والخدمات
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

  # حزم الفايربيز الأساسية للمشروع
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # الحزمة المسؤولة عن توليد أيقونات التطبيق للهواتف
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # تفعيل مجلد الـ assets العام للصور داخل التطبيق
  assets:
    - assets/

# إعدادات أيقونة التطبيق الرسمية للشاشة الخارجية
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"