// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuWskbRvLW24zXoYFZHacckUzpiOQ0iF8',
    appId: '1:698179864721:web:b8145ccb211844932e9730',
    messagingSenderId: '698179864721',
    projectId: 'projtrack-system',
    authDomain: 'projtrack-system.firebaseapp.com',
    storageBucket: 'projtrack-system.firebasestorage.app',
    measurementId: 'G-FE8DX1F5K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Ejb_B5b7vkx39OmcyZ666bjg_y_angU',
    appId: '1:698179864721:android:93548ef89519135c2e9730',
    messagingSenderId: '698179864721',
    projectId: 'projtrack-system',
    storageBucket: 'projtrack-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxeoHUwLB4Ek6VfM691eg9MV5c8v4ECDg',
    appId: '1:698179864721:ios:5827d0959bc8c91a2e9730',
    messagingSenderId: '698179864721',
    projectId: 'projtrack-system',
    storageBucket: 'projtrack-system.firebasestorage.app',
    iosBundleId: 'com.example.projtrackNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxeoHUwLB4Ek6VfM691eg9MV5c8v4ECDg',
    appId: '1:698179864721:ios:5827d0959bc8c91a2e9730',
    messagingSenderId: '698179864721',
    projectId: 'projtrack-system',
    storageBucket: 'projtrack-system.firebasestorage.app',
    iosBundleId: 'com.example.projtrackNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuWskbRvLW24zXoYFZHacckUzpiOQ0iF8',
    appId: '1:698179864721:web:04ed43d2bb7bfdce2e9730',
    messagingSenderId: '698179864721',
    projectId: 'projtrack-system',
    authDomain: 'projtrack-system.firebaseapp.com',
    storageBucket: 'projtrack-system.firebasestorage.app',
    measurementId: 'G-JK7G1SHXNJ',
  );
}
