platform :ios, '15.0'

require File.expand_path(File.join(File.dirname(__FILE__), '..', '.flutter-plugins-dependencies'))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # إعدادات الحزم القياسية لفلاتر
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # فرض تحديث إصدار iOS لكافة المكتبات والفايربيز إلى 15.0
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end